version: "3.8"

x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" http://minio{1...2}/data
  expose:
    - "9000"
    - "9090"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3



services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./minio-data1:/data
    networks:
      - minio-net

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ./minio-data2:/data
    networks:
      - minio-net
  nginx:
    image: nginx:latest
    container_name: minio-nginx
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio1
      - minio2
    networks:
      - minio-net
  db:
    image: postgres:latest
    container_name: minio-db
    environment:
      POSTGRES_DB: drive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    #entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypoint.sh"]
    networks:
      - minio-net
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    hostname: keycloak.quiz.local
    domainname: quiz.local
    ports:
      - "9080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: senha1234
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/drive
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    depends_on:
      - db
    command: ["start-dev","--http-host=0.0.0.0"]
    volumes:
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
      - ./keycloak-themes:/opt/jboss/keycloak/themes
      - ./keycloak-realm:/opt/jboss/keycloak/standalone/configuration/keycloak-realm.json
    
    networks:
      - minio-net
networks:
  minio-net: