/**
 * @fileoverview gRPC-Web generated client stub for logistics
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: logistic.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as logistic_pb from './logistic_pb'; // proto import: "logistic.proto"


export class CentralTrackingServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

}

export class DeliveryEstimateServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorEstimateDelivery = new grpcWeb.MethodDescriptor(
    '/logistics.DeliveryEstimateService/EstimateDelivery',
    grpcWeb.MethodType.UNARY,
    logistic_pb.EstimateRequest,
    logistic_pb.EstimateResponse,
    (request: logistic_pb.EstimateRequest) => {
      return request.serializeBinary();
    },
    logistic_pb.EstimateResponse.deserializeBinary
  );

  estimateDelivery(
    request: logistic_pb.EstimateRequest,
    metadata?: grpcWeb.Metadata | null): Promise<logistic_pb.EstimateResponse>;

  estimateDelivery(
    request: logistic_pb.EstimateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: logistic_pb.EstimateResponse) => void): grpcWeb.ClientReadableStream<logistic_pb.EstimateResponse>;

  estimateDelivery(
    request: logistic_pb.EstimateRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: logistic_pb.EstimateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/logistics.DeliveryEstimateService/EstimateDelivery',
        request,
        metadata || {},
        this.methodDescriptorEstimateDelivery,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/logistics.DeliveryEstimateService/EstimateDelivery',
    request,
    metadata || {},
    this.methodDescriptorEstimateDelivery);
  }

}

